
objs-y += main.o
objs-y += ws.o
objs-y += render.o
objs-y += outputs.o
objs-y += config_yabr.o
objs-y += lemonbar.o
objs-y += i3.o
objs-y += notif_dbus.o

subdir-y += status
objs-y += status_conf.o

subdir-y += config

